### PR TITLE
Fix issue with missing identifier from ActiveRecord

### LINKED ISSUE #19: Error generating report
**Describe the bug**

```ruby
ArgumentError:
  comparison of Array with Array failed
# (erb):12:in `sort_by'
# (erb):12:in `<main>'
# ./spec/rails_helper.rb:93:in `block (2 levels) in <top (required)>'
```

**To Reproduce**
Unsure without sharing code at this point, here is the line I use to generate the report:

```ruby
WtActiverecordIndexSpy.export_html_results(File.new(File.join(Rails.root, "tmp/wt_activerecord_index_spy-results.html"), "w"))
```

Issue is here https://github.com/WeTransfer/wt_activerecord_index_spy/blob/main/lib/wt_activerecord_index_spy/results.html.erb#L12

**Expected behavior**
Report generated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Database/version: MySql 5.7
 - Ruby version: Ruby 2.7.2
 - Activerecord version: Rails 5.2.4.6

### PR DESCRIPTION
**Pull request by lloydwatkin**
## Description

If `ActiveRecord` does not provide an identifier this causes the output to fail. This update simply stringifies the identifier so a crash does not happen.

Fixes #19

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

* Locally using code which currently fails
* Unit test added

## Checklist:

- [x] My code follows the style guidelines set by rubocop
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by fabioperrella — CHANGES_REQUESTED** [review]
Hey @lloydwatkin , thanks for your contribution!! Could you pls check the errors on CI?

**Comment by lloydwatkin** [comment]
Yeah looks like I didn't use valid postgesql syntax (only have mySQL locally). Will get this fixed up tomorrow morning 👍

File: spec/lib/wt_activerecord_index_spy/notification_listener_spec.rb [hunk 1]
```diff
@@ -15,11 +15,23 @@
     expect(aggregator.uncertain_results.count).to eq(0)
   end
 
+  describe 'Identifier not provided by ActiveRecord' do
+    let(:values) do
+      { sql: 'SELECT * FROM users WHERE name = "lala"' }
+    end
+
+    it 'defaults to empty string if identifier not provided' do
```
Comment (fabioperrella) [inline spec/lib/wt_activerecord_index_spy/notification_listener_spec.rb:23]: This test is still broken for Postgres. I think you have to do these things:
- change double quotes by single quotes
```diff
-'SELECT * FROM users WHERE name = "lala"'
+"SELECT * FROM users WHERE name = 'lala'"
```
- create another IT to test Postgres, because currently all results of Postgres are uncertain OR test only MySQL, which I think is ok, given the fix you did works for both

**Comment by lloydwatkin** [comment]
@fabioperrella apologies, its been a while since I've worked with postgressql and I tried to use the quick route (rather than installing it and testing). All updated now :+1:

**Comment by fabioperrella** [comment]
No problem!

Could you pls take a look at the failure on CI pls?

**Comment by lloydwatkin** [comment]
Didn't push all local changes, now pushed.

**Review by fabioperrella — APPROVED** [review]
great!
